CREATE DATABASE   IF NOT EXISTS `archive_lottery`   DEFAULT CHARACTER SET utf8;
-- ----------------------------
-- Table structure for `ticket`
-- ----------------------------
DROP TABLE IF EXISTS `ticket_archive`;

CREATE TABLE `ticket_archive` (
  `id` varchar(255) NOT NULL,
  `addition` int(11) DEFAULT NULL,
  `amount` decimal(19,2) NOT NULL,
  `batch_id` varchar(255) DEFAULT NULL,
  `batch_index` bigint(20) DEFAULT NULL,
  `content` varchar(255) NOT NULL,
  `create_time` timestamp(6) NULL DEFAULT NULL,
  `dead_line` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  `draw_time` timestamp(6) NULL DEFAULT NULL,
  `exchange_time` timestamp(6) NULL DEFAULT NULL,
  `external_id` varchar(255) DEFAULT NULL,
  `failure_message` varchar(255) DEFAULT NULL,
  `failure_type` int(11) DEFAULT NULL,
  `is_exchanged` int(11) DEFAULT NULL,
  `lottery_type` int(11) NOT NULL,
  `multiple` int(11) NOT NULL,
  `orderid` varchar(255) NOT NULL,
  `passwd` varchar(255) DEFAULT NULL,
  `peilv` text,
  `phase` varchar(255) DEFAULT NULL,
  `play_type` int(11) NOT NULL,
  `posttax_prize` decimal(19,2) DEFAULT NULL,
  `pretax_prize` decimal(19,2) DEFAULT NULL,
  `print_time` timestamp(6) NULL DEFAULT NULL,
  `prize_detail` varchar(255) DEFAULT NULL,
  `send_time` timestamp(6) NULL DEFAULT NULL,
  `status` int(11) NOT NULL,
  `terminal_id` bigint(20) DEFAULT NULL,
  `terminal_type` int(10) DEFAULT NULL,
  `terminate_time` timestamp(6) NULL DEFAULT NULL,
  `ticket_result_status` int(11) DEFAULT NULL,
  `userno` varchar(255) NOT NULL,
  `total_prize` decimal(19,2) DEFAULT '0.00',
  `add_prize` decimal(19,2) DEFAULT '0.00',
  `user_name` varchar(255) DEFAULT NULL,
  `real_name` varchar(255) DEFAULT NULL,
  `send_time_long` bigint(32) DEFAULT '0',
  `dead_time_long` bigint(32) DEFAULT '0',
  `match_nums` text,
  `first_matchnum` bigint(20) DEFAULT '0',
  `last_matchnum` bigint(20) DEFAULT '0',
  `agency_prize` decimal(19,2) DEFAULT '0.00',
  `agency_exchanged` int(10) DEFAULT '0',
  `machine_code` varchar(200) DEFAULT '0',
  `sell_run_code` varchar(200) DEFAULT '0',
  `md5_code` varchar(200) DEFAULT '0',
  `agent_id` varchar(255) NOT NULL DEFAULT '0',
  `order_amount` decimal(19,2) DEFAULT '0.00',
  `ticket_end_time` timestamp(6) NULL DEFAULT NULL,
  `serial_id` varchar(4000) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `lottery_order_archive`;

CREATE TABLE `lottery_order_archive` (
  `id` varchar(255) NOT NULL,
  `account_type` int(11) DEFAULT NULL,
  `adddition` int(11) DEFAULT NULL,
  `agencyno` varchar(255) DEFAULT NULL,
  `amount` decimal(19,2) NOT NULL,
  `amt` decimal(19,2) NOT NULL,
  `bet_type` int(11) DEFAULT NULL,
  `big_posttaxprize` decimal(19,2) DEFAULT NULL,
  `byuserno` varchar(255) NOT NULL,
  `chase_id` varchar(255) DEFAULT NULL,
  `content` longtext NOT NULL,
  `dead_line` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  `draw_time` timestamp(6) NULL DEFAULT NULL,
  `first_matchnum` bigint(20) DEFAULT '0',
  `hemaiid` varchar(255) DEFAULT NULL,
  `is_exchanged` int(3) DEFAULT NULL,
  `last_matchnum` bigint(20) DEFAULT NULL,
  `lottery_type` int(11) NOT NULL,
  `match_nums` text,
  `multiple` int(11) NOT NULL,
  `order_result_status` int(3) DEFAULT NULL,
  `order_status` int(11) NOT NULL,
  `pay_status` int(11) NOT NULL,
  `phase` varchar(255) DEFAULT NULL,
  `pretax_prize` decimal(19,2) DEFAULT NULL,
  `print_time` timestamp(6) NULL DEFAULT NULL,
  `prize_detail` varchar(255) DEFAULT NULL,
  `process_time` timestamp(6) NULL DEFAULT NULL,
  `receive_time` timestamp(6) NOT NULL DEFAULT '0000-00-00 00:00:00.000000',
  `reward_time` timestamp(6) NULL DEFAULT NULL,
  `small_posttaxprize` decimal(19,2) DEFAULT NULL,
  `terminalid` varchar(255) DEFAULT NULL,
  `terminal_type_id` int(11) DEFAULT NULL,
  `userno` varchar(255) NOT NULL,
  `wincode` varchar(255) DEFAULT NULL,
  `play_type_str` varchar(4000) DEFAULT NULL,
  `total_prize` decimal(19,2) DEFAULT '0.00',
  `add_prize` decimal(19,2) DEFAULT '0.00',
  `user_name` varchar(255) DEFAULT NULL,
  `real_name` varchar(255) DEFAULT NULL,
  `buy_agencyno` varchar(200) DEFAULT '0',
  `agent_id` varchar(255) NOT NULL DEFAULT '0',
  `ticket_count` bigint(15) DEFAULT '0',
  `fail_count` bigint(15) DEFAULT '0',
  `prize_optimize` int(5) DEFAULT '0',
  `order_amount` decimal(19,2) NOT NULL DEFAULT '0.00',
  `code_filter` int(2) NOT NULL DEFAULT '0',
  `memo` varchar(255) DEFAULT '',
  `preferential_amount` decimal(19,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `user_account_detail_archive`;

CREATE TABLE `user_account_detail_archive` (
  `id` varchar(255) NOT NULL,
  `amt` decimal(19,2) NOT NULL,
  `balance` decimal(19,2) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `create_time` timestamp(6) NULL DEFAULT NULL,
  `account_detail_type` int(11) NOT NULL,
  `draw_balance` decimal(19,2) DEFAULT NULL,
  `freeze` decimal(19,2) DEFAULT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `otherid` varchar(255) DEFAULT NULL,
  `payid` varchar(255) NOT NULL,
  `pay_type` int(11) NOT NULL,
  `userno` varchar(255) NOT NULL,
  `sign_status` int(4) DEFAULT '0',
  `finish_time` datetime(6) DEFAULT NULL,
  `lottery_type` int(10) DEFAULT '0',
  `phase` varchar(200) DEFAULT '0',
  `draw_amount` decimal(19,2) DEFAULT '0.00',
  `not_draw_amount` decimal(19,2) DEFAULT '0.00',
  `give_amount` decimal(19,2) DEFAULT '0.00',
  `agency_no` varchar(200) DEFAULT '0',
  `user_name` varchar(255) NOT NULL DEFAULT '0',
  `order_prize_amount` decimal(19,2) DEFAULT '0.00',
  `order_prize_type` int(5) DEFAULT '0',
  `orderid` varchar(255) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;